
server:
  port: 8888

spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/SarahTumenas/microservices-spring-cloud/tree/microservice-repo
          search-paths: fornecedor, loja
